### ISSUE TITLE
Bike-shedding the name

### ISSUE THREAD

**Issue by kescobo** [BioJulia/NCBIBlast.jl#1]
One other option I considered was `BLASTPlus.jl`. `BLAST.jl` is available, but seems too generic to make sense.

**Comment by hodgensc** [comment]
I agree that BLAST.jl is too generic - that would make me think it was an umbrella BLAST tool or a complete reimplementation or something other than just a wrapper for BLAST+. I think either BLASTPlus or NCBIBLAST are fine. They both make it clear that you're referring to a specific BLAST implementation rather than the tool in general. 

NCBIBlast is probably the safer name; my (small) concern is one might see a plain BLASTPlus.jl package and assume it was an official BLAST+ implementation in Julia or something. Probably I'm just worrying about nothing. Or maybe someone would think NCBIBlast.jl indicates that NCBI built it. Who knows. I can't think of a good reason to prefer one over the other and you already registered this name, so keeping it as-is is fine IMO.

**Comment by kescobo** [comment]
I haven't actually registered this yet, so it would not be hard to change at this stage.

I don't think there's a way to avoid potential confusion with the name alone, but hopefully it can be clear in the README / description. Should I add a bit more explicit statements that this is an unofficial wrapper?

**Comment by hodgensc** [comment]
You're right, the README makes it clear it's just a wrapper. So I think it's fine as-is.

If you haven't registered it yet, I guess it's just a question of name preference? The only thing that comes to mind about one vs the other is the capitalization. Right now it's NCBIBlast, but BLAST is technically an acronym, so maybe NCBIBLAST? Other than that very minor point I have no preference either way.

**Comment by jakobnissen** [comment]
I like NCBIBlast. It's clear, not too long, and doesn't hog Blast.jl.

**Comment by kescobo** [comment]
https://github.com/JuliaRegistries/General/pull/116900
